name: GitHub Actions Demo
run-name: GitHub Actions Demo

on:
  push:
    branches:      
      - '*'        # 所有分支
  workflow_dispatch:  # 可以手動執行

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo '執行成功'
